### ISSUE TITLE
"Error:Can't trade[ask]"が出続けます

### ISSUE THREAD

**Issue by shikamura128** [kichie/zaif-auto-trade#2]
プログラム利用させていただきました。
注文がほぼ通らずに"Error:Can't trade[ask]"がで続けていますが、これはzaifのサーバーが悪いということでしょうか

**Comment by kichie** [comment]
有難うございます。上記のエラーメッセージは取引の売り注文をする時に発生するエラーメッセージです。考えられる点として、資産情報は取得できていると考えられるので、売り注文を出すときに資産が足りていない可能性があります。もしくは、btcの資産が0.001以上すでにお持ちで予期せぬ動作が起きている可能性が考えられます、ご確認お願いします。
